### ISSUE TITLE
Jump, Sprint, Run Buttons Need to Be Assigned for Keyboard

### ISSUE THREAD

**Issue by calben** [calben/networked-third-person-player-controller#2]
Currently there are no buttons for jump, sprint, run, etc.
These need to be assigned and configured for the Mac and Windows keyboard.

Probably space for jump, left shift for run, and alt for sprint.

Both run and sprint key must be pressed in order for the user to sprint.
On keyboard, this deprives user of two fingers, which makes taking actions while sprinting more difficult (makes sense).
On gamepad, this means using both left stick buttons, making the sticks a little less comfortable to use.

**Comment by mpabin** [comment]
CONTROLS:
jump: space
run: left shift
sprint: C

--aiming for keyboard still needs to be implemented

**Comment by calben** [comment]
Looks like this is done!
